spring:
  datasource:
    url: jdbc:mariadb://211.37.147.89:3306
    driver-class-name: org.mariadb.jdbc.Driver
    username: "semo"
    password: "h9124"
  jackson:
    property-naming-strategy: com.semobook.config.CustomNamingStrategy
    mapper:
      use-std-bean-naming: true
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
