spring:
  datasource:
    url: jdbc:mariadb://211.37.147.89:3306/semo
    driver-class-name: org.mariadb.jdbc.Driver
    username: "semo"
    password: "h9124"
  jackson:
    property-naming-strategy: com.semobook.config.CustomNamingStrategy
    mapper:
      use-std-bean-naming: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: trace